name: Build ThunderExtensions on MacOS

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/MacOS build template.yml@master

  ThunderExtensions:
    needs: Thunder
    uses: ./.github/workflows/MacOS build template.yml
